Ошибка подключения к Oracle: Python value of type set not supported.
